### ISSUE TITLE
Project Details

### ISSUE THREAD

**Issue by mzbhewtee** [Konyancha1/BacchusApp#1]
I think we need to have some things to consider first before building the app.
1. Research
2. User story
3. use case
4. App requirements
5. Project architecture
6. wireframe
7. brief meeting
8. frontend
9. Backend
10. Test

**Comment by Konyancha1** [comment]
Yes, we do need to do these but I'm creating this repo so that we can kick-start the project. Let me talk to one of the people I think whom this project would benefit as since we are thinking of linking customers to markets through this app right?

**Comment by mzbhewtee** [comment]
Alright
